version: '3.4'

services:
  web:
    image: djangoweb
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 
    ports:
      - 1234:8000
    env_file:
      - ./.env
